### ISSUE TITLE
January 29th in Gregorian calendar sets March 1st on click

### ISSUE THREAD

**Issue by martinmikulka** [babakhani/pwt.datepicker#210] opened 2018-02-09 15:05 UTC
Hi, there is something wrong on month view of January. There is missing 29th, instead there is 1st. When clicked, the 1st of March is set. 

Please check. 

![january](https://user-images.githubusercontent.com/8431259/36034005-dbfaaf0c-0db2-11e8-8cdd-11e18de54e01.png)

**Comment by martinmikulka** [comment] 2018-02-09 15:09
There is probably some relation with days number in leap-year. Here is screenshot of January 2020.

![image](https://user-images.githubusercontent.com/8431259/36034115-49b4e210-0db3-11e8-93b0-94a6407b8a2b.png)

**Comment by babakhani** [comment] 2018-02-10 15:21
@martinmikulka 
i check this on [Playground](http://babakhani.github.io/PersianWebToolkit/doc/datepicker/playground.html) and everything seems well.
can you give us more details about your configuration?


![screen shot 1396-11-21 at 6 45 19 pm](https://user-images.githubusercontent.com/3070333/36063490-d5d0f434-0e92-11e8-8023-9b935e8e6036.png)
![screen shot 1396-11-21 at 6 45 34 pm](https://user-images.githubusercontent.com/3070333/36063491-d640fdce-0e92-11e8-98b9-5c78d22fd598.png)

**Comment by martinmikulka** [comment] 2018-02-13 10:42
Hello, it seems that problem was at PersianDate library. I updated from version 1.0.1 to 1.0.5 and now it works correctly.

In case you will check PersianDatepicker with the PersianDate 1.0.1, please note, that problem is not only in the last day of January, but the whole month is rendered incorrectly. When January is displayed, all rendered days belong to February.

![image](https://user-images.githubusercontent.com/8431259/36145809-cbc6bdda-10b2-11e8-995b-cc6e05ceda6a.png)


![image](https://user-images.githubusercontent.com/8431259/36145771-a8e3f45e-10b2-11e8-909c-f95ef7655822.png)

**Comment by babakhani** [comment] 2018-02-13 16:08
@martinmikulka 
I think it's duplicate of #183 
thank you anyways

**Closed by babakhani** 2018-02-13 16:08 UTC
